import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

#if os(Linux) || os(FreeBSD)
   @testable import AppTests

// This protocol is necessary to we can call the 'run' method (on an existential of this protocol)
// without the compiler noticing that we're calling a deprecated function.
// This hack exists so we can deprecate individual tests which test deprecated functionality without
// getting a compiler warning...
protocol LinuxMainRunner { func run() }
class LinuxMainRunnerImpl: LinuxMainRunner {
   @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
   func run() {
       XCTMain([
             testCase(BlogCategoryCollectionTests.allTests),
             testCase(BlogCollectionTests.allTests),
             testCase(EducationCollectionTests.allTests),
             testCase(ExpCollectionTests.allTests),
             testCase(FileCollectionTests.allTests),
             testCase(IndustryCollectionTests.allTests),
             testCase(LogCollectionTests.allTests),
             testCase(ProjCollectionTests.allTests),
             testCase(SkillCollectionTests.allTests),
             testCase(SocialNetworkingCollectionTests.allTests),
             testCase(SocialNetworkingSereviceCollectionTests.allTests),
             testCase(UserCollectionTests.allTests),
        ])
    }
}
(LinuxMainRunnerImpl() as LinuxMainRunner).run()
#endif
