# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#

x-mysql: &mysql
  MYSQL_USER: swift
  MYSQL_PASSWORD: mysql
  MYSQL_DATABASE: blog

services:

  test:
    image: swift-blog-tests
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      MYSQL_HOST: db
      <<: *mysql
    volumes:
      - ..:/code:z
    working_dir: /code
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE
    depends_on: [db]
    command: python3 build-script.py --test

  db:
    image: mysql:latest
    environment:
      <<: *mysql
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      LANG: C.UTF-8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
