FROM swift:5.6-focal

RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true

# Install OS updates and set as UTF-8
RUN apt-get -q update \
    && apt-get -q dist-upgrade -y \
    && apt-get -q install -y locales locales-all python3 \
    && rm -rf /var/lib/apt/lists/*

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
