import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension EduExpCollectionTests {

   @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
   static var allTests : [(String, (EduExpCollectionTests) -> () throws -> Void)] {
      return [
                ("testAuthorizeRequire", testAuthorizeRequire),
                ("testCreate", testCreate),
                ("testQueryWithInvalidEduID", testQueryWithInvalidEduID),
                ("testQueryWithEduID", testQueryWithEduID),
                ("testUpdate", testUpdate),
                ("testDeleteWithInvalideduID", testDeleteWithInvalideduID),
                ("testDelete", testDelete),
           ]
   }
}

