import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension IndustryCollectionTests {

   @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
   static var allTests : [(String, (IndustryCollectionTests) -> () throws -> Void)] {
      return [
                ("testCreate", testCreate),
                ("testCreateWithConflictIndustry", testCreateWithConflictIndustry),
                ("testQueryWithInvalidID", testQueryWithInvalidID),
                ("testQueryWithID", testQueryWithID),
                ("testQueryAll", testQueryAll),
                ("testUpdate", testUpdate),
                ("testDelete", testDelete),
           ]
   }
}

