import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.py
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension ProjCollectionTests {

    @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
    static var allTests: [(String, (ProjCollectionTests) -> () throws -> Void)] {
        return [
            ("testAuthorizeRequire", testAuthorizeRequire),
            ("testCreate", testCreate),
            ("testQueryWithInvalidWorkID", testQueryWithInvalidWorkID),
            ("testQueryWithWorkID", testQueryWithWorkID),
            ("testUpdate", testUpdate),
            ("testDeleteWithInvalidWorkID", testDeleteWithInvalidWorkID),
            ("testDelete", testDelete),
        ]
    }
}
