import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.py
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension SkillCollectionTests {

    @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
    static var allTests: [(String, (SkillCollectionTests) -> () throws -> Void)] {
        return [
            ("testAuthorizeRequire", testAuthorizeRequire),
            ("testCreate", testCreate),
            ("testCreateWithoutWorkflow", testCreateWithoutWorkflow),
            ("testCreateWithInvalidDataType", testCreateWithInvalidDataType),
            ("testQuery", testQuery),
            ("testQueryWithInvalidID", testQueryWithInvalidID),
            ("testUpdate", testUpdate),
            ("testUpdateWithInvalidID", testUpdateWithInvalidID),
            ("testDelete", testDelete),
            ("testDeleteWithInvalidID", testDeleteWithInvalidID),
        ]
    }
}
