import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.py
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension SocialNetworkingCollectionTests {

    @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
    static var allTests: [(String, (SocialNetworkingCollectionTests) -> () throws -> Void)] {
        return [
            ("testCreate", testCreate),
            ("testAuthorizeRequire", testAuthorizeRequire),
            ("testQueryWithInvalidID", testQueryWithInvalidID),
            ("testQueryWithSocialID", testQueryWithSocialID),
            ("testUpdate", testUpdate),
            ("testDelete", testDelete),
        ]
    }
}
