//===----------------------------------------------------------------------===//
//
// This source file is part of the website-backend open source project
//
// Copyright © 2020 Eli Zhang and the website-backend project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// SocialNetworkingSereviceCollectionTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension SocialNetworkingSereviceCollectionTests {

   @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
   static var allTests : [(String, (SocialNetworkingSereviceCollectionTests) -> () throws -> Void)] {
      return [
                ("testCreate", testCreate),
                ("testQueryWithInvalidID", testQueryWithInvalidID),
                ("testQueryWithServiceID", testQueryWithServiceID),
                ("testUpdate", testUpdate),
                ("testDeleteWithInvalidServiceID", testDeleteWithInvalidServiceID),
                ("testDelete", testDelete),
           ]
   }
}

