//===----------------------------------------------------------------------===//
//
// This source file is part of the website-backend open source project
//
// Copyright © 2020 Eli Zhang and the website-backend project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// UserCollectionTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension UserCollectionTests {

   @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
   static var allTests : [(String, (UserCollectionTests) -> () throws -> Void)] {
      return [
                ("testAuthorizeRequire", testAuthorizeRequire),
                ("testCreateWithInvalidUsername", testCreateWithInvalidUsername),
                ("testCreateWithInvalidPassword", testCreateWithInvalidPassword),
                ("testCreateWithConflictUsername", testCreateWithConflictUsername),
                ("testCreate", testCreate),
                ("testQueryWithInvalidUserID", testQueryWithInvalidUserID),
                ("testQueryWithUserID", testQueryWithUserID),
                ("testQueryWithUserIDAndQueryParameters", testQueryWithUserIDAndQueryParameters),
                ("testQueryWithUserIDAndQueryParametersAfterAddChildrens", testQueryWithUserIDAndQueryParametersAfterAddChildrens),
                ("testQueryAll", testQueryAll),
                ("testQueryAllWithQueryParametersAfterAddChildrens", testQueryAllWithQueryParametersAfterAddChildrens),
                ("testUpdate", testUpdate),
           ]
   }
}

