name: CI

on: [ push, pull_request]

jobs:
  test:
    container: swift:5.2
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_USER: vapor
          MYSQL_PASSWORD: vapor.mysql
          MYSQL_DATABASE: website
    steps:
      - name: Check out test case
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        env:
          MYSQL_HOSTNAME: mysql
        run: swift test --enable-test-discovery --sanitize=thread

  push_to_registry:
    if: ${{ startsWith(github.ref, 'refs/tags/*') }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker to registry
        uses: docker/build-push-action@v1.1.0
        with:
          dockerfile: ./docker/Dockerfile
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tags: latest
