name: Build and Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        db:
          - mysql:latest
    container: swift:latest
    runs-on: ubuntu-latest
    services:
      mysql:
        image: ${{ matrix.db }}
        env:
          MYSQL_USER: swift 
          MYSQL_PASSWORD: mysql
          MYSQL_DATABASE: blog
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install rsync
        run: apt -q update && apt -q dist-upgrade -y && apt -q install -y rsync

      - name: Setup Python to latest...
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Run tests
        env:
          MYSQL_HOST: mysql
        run: python build-script.py --test

  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Test docker compose
        run: |
          docker compose -f docker/compose.test.yaml run --rm test
