name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        dbimage:
          - mysql:latest
    container: swift:5.3
    runs-on: ubuntu-latest
    services:
      mysql:
        image: ${{ matrix.dbimage }}
        env:
          MYSQL_USER: mysql.user
          MYSQL_PASSWORD: mysql.pwd
          MYSQL_DATABASE: website_testing
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    steps:
      - name: Check out test case
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        env:
          MYSQL_HOST: mysql
        run: swift test --enable-test-discovery --sanitize=thread

  push_to_registry:
    if: ${{ startsWith(github.ref, 'refs/tags/*') }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker to registry
        uses: docker/build-push-action@v1.1.0
        with:
          dockerfile: ./docker/Dockerfile
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tags: latest
