name: Build and Tests

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**/*.md'
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository...
        uses: actions/checkout@v3

      - name: Run tests...
        run: |
          docker compose -f docker/compose.test.yaml build
          docker compose -f docker/compose.test.yaml run --rm test
