name: 'Test on push master and pull request'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    container: swift:5.2
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_USER: vapor
          MYSQL_PASSWORD: vapor.mysql
          MYSQL_DATABASE: website

    steps:
      - name: Check out test case
        uses: actions/checkout@v2

      - name: Run tests with Thread Sanitizer
        run: swift test --enable-test-discovery --sanitize=thread
        env:
          MYSQL_HOSTNAME: mysql
